# .readthedocs.yml

version: 2

python:
   version: 3.6
   install:
      - requirements: requirements.txt
      - method: setuptools
        path: .
   system_packages: true
sphinx:
  builder: html
  configuration: docs/conf.py

requirements_file: requirements.txt

formats:
    - epub
    - pdf