# .readthedocs.yml

version: 2

build:
  image: latest

python:
  version: 3.6
  setup_py_install: True

sphinx:
  builder: html
  configuration: docs/conf.py

requirements_file: requirements.txt

formats:
    - epub
    - pdf