site_name: scNet Documentation
site_description: 'Documentation for ScNet'
docs_dir: docs/sources
repo_url: http://github.com/theislab/scnet

pages:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Models:
    - scNet: 'models/scNet.md'
    - utils: 'utils.md'
    - metrics: 'metrics.md'
    - plotting: 'plotting.md'

theme: readthedocs